import { downloadZip } from 'client-zip';
import type { ExportFile } from './exporter';

export function buildReadme(counts: Record<string, number>, storeName: string): string {
  const lines = [
    'STOCKY RESCUE EXPORT',
    `Store: ${storeName}`,
    `Exported: ${new Date().toISOString()}`,
    '',
    'Files:',
  ];
  for (const [resource, count] of Object.entries(counts)) {
    if (resource === 'purchase_orders') {
      lines.push(`- purchase_orders.csv (${count} rows)`);
      lines.push('- purchase_order_line_items.csv (line items of the orders above)');
    } else {
      lines.push(`- ${resource}.csv (${count} rows)`);
    }
  }
  lines.push(
    '',
    'IMPORTANT: Stocky and its API shut down on August 31, 2026.',
    'After that date this data cannot be re-exported. Keep this file safe.',
    '',
    'Generated by Stocky Rescue - free & open source.',
    'We are building a replacement for what Shopify did not keep',
    '(reorder suggestions + supplier management). https://stocky-rescue.pages.dev'
  );
  return lines.join('\n');
}

export function buildErrorsFile(errors: string[]): string | null {
  if (errors.length === 0) return null;
  return [
    'Some resources could not be exported:',
    '',
    ...errors.map((e) => `- ${e}`),
    '',
    'If the error is HTTP 404, your Stocky plan may not include that feature - nothing to retry.',
    'For other errors you can retry: re-run the export on the site. Completed files in this ZIP are fine.',
  ].join('\n');
}

export async function buildZipBlob(
  files: ExportFile[], counts: Record<string, number>, errors: string[], storeName: string
): Promise<Blob> {
  const entries = [
    ...files.map((f) => ({ name: f.name, input: f.content })),
    { name: 'README.txt', input: buildReadme(counts, storeName) },
  ];
  const errTxt = buildErrorsFile(errors);
  if (errTxt) entries.push({ name: 'ERRORS.txt', input: errTxt });
  return await downloadZip(entries).blob();
}
